services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "15MB"
  db:
    image: postgres:15
    container_name: db
    hostname: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: rinha
      POSTGRES_PASSWORD: rinhapass
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rinha" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - backend
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "275MB"
  api1: &api
    build:
      context: .
      dockerfile: Dockerfile
    hostname: api1
    container_name: api1
    environment:
      - SERVER_PORT=8081
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - EXECUTE_HEALTH_CHECK=true
      - DB_URL=r2dbc:postgresql://db:5432/postgres
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: "curl --fail --silent localhost:8081/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 10s
    networks:
      - backend
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: "512MB"

  api2:
    <<: *api
    hostname: api2
    container_name: api2
    healthcheck:
      test: "curl --fail --silent localhost:8082/health | grep UP || exit 1"
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 60s
    environment:
      - SERVER_PORT=8082
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - DB_URL=r2dbc:postgresql://db:5432/postgres
      - EXECUTE_HEALTH_CHECK=false

#  redis:
#    image: redis:7.2-alpine
#    container_name: rinha-redis
#    command: redis-server --save "" --appendonly no --maxclients 20000
#    networks:
#      - backend
#    healthcheck:
#      test: ["CMD", "redis-cli", "ping"]
#      interval: 5s
#      timeout: 5s
#      retries: 5
#    deploy:
#      resources:
#        limits:
#          cpus: "0.25"
#          memory: "275MB"

networks:
  backend:
    driver: bridge
    name: backend
  payment-processor:
    external: true